# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vibeTwo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vibeTwo

  target 'vibeTwo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vibeTwoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'vibeTwo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vibeTwo-tvOS

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
